name: Build And Deploy WebGL

on:
  workflow_dispatch:  #手動でワークフローを始められる
  push:               #リポジトリにプッシュしたとき
  pull_request:
    types: ["closed"] #プルリクエストがクローズされたとき
    branches:
      - main           #対象ブランチ

jobs:  
  ubuntu-build:             #ジョブの名前
    runs-on: ubuntu-latest  #ワークフロー内の仮想マシンの種類

    permissions:              #ワークフロー対して権限を与えるセクション
      checks: write           #書き込み権限
      contents: write         #リポジトリへの書き込み権限

    steps:
      - name: Checkout              
        uses: actions/checkout@v6.0.0  #チェックアウトでリポジトリのコードをワークフロー内に取り込む

      - name: Cache library #キャッシュを作る
        uses: actions/cache@v4.3.0
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**','Packages/**','ProjectSettings/**') }}
          restore-keys: Library-

      - name: Build Project #ここでビルド
        uses: game-ci/unity-builder@v4.8.1  #GameCIのUnity_builderを使用
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with: 
          targetPlatform: WebGL         #ビルドするプラットフォーム
          unityVersion: auto            #使用するUnityエディタのバージョン　EditorVersion.txt内に書いている内容
          projectPath: .    #リポジトリのUnityプロジェクトのパス プロジェクト名を入れる

      - name: Upload artifacts  #ビルドの成果物を保存
        uses: actions/upload-artifact@v5.0.0
        with:
          name: WebGL-Build
          path: build/WebGL